/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'

const rootRoute = rootRouteImport

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

export interface FileRoutesByPath {
  '/': {
    id: '/'
    path: '/'
    fullPath: '/'
    preLoaderRoute: typeof IndexRouteImport
    parentRoute: typeof rootRoute
  }
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': FileRoutesByPath['/']
  }
}

const _rootRouteChildren: any = {
  IndexRoute: IndexRoute,
}

export const routeTree = rootRoute._addFileChildren(_rootRouteChildren)
